---
title: "'Catch' block never reached; <exception> handled above in the same 'Try' statement"
ms.date: 07/20/2015
f1_keywords: 
  - "bc42031"
  - "vbc42031"
helpviewer_keywords: 
  - "BC42031"
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
---
# 'Catch' block never reached; \<exception> handled above in the same 'Try' statement
A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.  
  
 By default, this message is a warning. For more information about hiding warnings or treating warnings as errors, please see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **Error ID:** BC42031  
  
## To correct this error  
  
-   Remove the redundant statement.  
  
## See also
- [How to: Catch an Exception in Visual Basic](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/ys1b32h3(v=vs.100))
- [How to: Test Code with a Tryâ€¦Catch Block in Visual Basic](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/8tbkaxz5(v=vs.100))
- [How to: Filter Errors in a Catch Block in Visual Basic](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/79dh1480(v=vs.100))
- [Walkthrough: Structured Exception Handling (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/8c522k35(v=vs.100))
- [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
